name: Test

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - '.github/workflows/test.yml'
    pull_request:
      branches: [ master ]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dotnet: [6.0.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Build projects
        working-directory: ./src/
        run: dotnet build

      - name: Run unit tests
        working-directory: ./src/ODataHttpClient.Tests
        shell: bash
        run: |
          dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=lcov
          bash <(curl -s https://codecov.io/bash)